name: hello world

on:
  push: 


jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v4   #sert à recup le code de la branche qui a déclenché la pipeline

      - run : echo "hello world"